version: "3.6"

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  webapi.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
